name: Publish Latest
on:
  push:
    tags:
      - latest
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
      - name: Compress binary
        run: strip target/release/migration
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/migration"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true